pipeline {
    agent any

    stages {
        stage('Prepare Environment') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'ansible-credentials', usernameVariable: 'ANSIBLE_USER', passwordVariable: 'ANSIBLE_PASS')]) {
                    ansiblePlaybook(
                        playbook: 'ansible/prepare_environment.yml',
                        inventory: 'inventory/hosts',
                        extraVars: [
                            ansible_ssh_pass: "${ANSIBLE_PASS}"
                        ]
                    )
                }
            }
        }

        stage('Start Applications') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'ansible-credentials', usernameVariable: 'ANSIBLE_USER', passwordVariable: 'ANSIBLE_PASS')]) {
                    ansiblePlaybook(
                        playbook: 'ansible/start_applications.yml',
                        inventory: 'inventory/hosts',
                        extraVars: [
                            ansible_ssh_pass: "${ANSIBLE_PASS}"
                        ]
                    )
                }
            }
        }
    }
}
