# Файл конфигурации для Docker Compose

# Описание сервисов
services:
  # Сервис backend1
  backend1:
    # Путь к директории с файлом Dockerfile для сборки образа
    build: ./DevOps/backend1
    # Порты, которые будут доступны извне контейнера
    ports:
      - "5000:5000"
    # Переменные окружения для сервиса
    environment:
      FLASK_APP: backend1
    # Команда для запуска сервиса
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000"]
    # Зависимости от других сервисов
    depends_on: []
    # Сеть, к которой будет подключен сервис
    networks:
      - backend-network

  # Сервис frontend1
  frontend1:
    # Путь к директории с файлом Dockerfile для сборки образа
    build: ./DevOps/frontend1
    # Порты, которые будут доступны извне контейнера
    ports:
      - "5002:5002"
    # Переменные окружения для сервиса
    environment:
      XDG_RUNTIME_DIR: /tmp/runtime-dir
    # Команда для запуска сервиса
    command: ["python", "frontend1.py"]
    # Зависимости от других сервисов
    depends_on:
      - backend1
    # Сеть, к которой будет подключен сервис
    networks:
      backend-network:
        # Алиасы для сети
        aliases:
          - localhost
    # Дополнительные хосты для сети
    extra_hosts:
      - "localhost:host-gateway"

  # Сервис nginx
  nginx:
    # Образ для сервиса
    image: nginx:latest
    # Порты, которые будут доступны извне контейнера
    ports:
      - "80:80"
    # Том, который будет монтирован в контейнер
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    # Зависимости от других сервисов
    depends_on:
      - backend1
      - frontend1
    # Сеть, к которой будет подключен сервис
    networks:
      - backend-network

# Описание сетей
networks:
  # Сеть backend-network
  backend-network:
    # Драйвер для сети
    driver: bridge
