version: '3'

services:
  backend1:
    build: ./DevOps/backend1
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: backend1
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000"]
    depends_on: []

  frontend1:
    build: ./DevOps/frontend1
    ports:
      - "5002:5002"
    environment:
      XDG_RUNTIME_DIR: /tmp/runtime-dir
      BACKEND_URL: http://backend1:5000  # Set the backend URL here
    depends_on:
      - backend1
    command: ["python", "frontend1.py", "${BACKEND_URL}"]  # Pass the BACKEND_URL as an argument to frontend1.py

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - frontend1
