services:
  front:
    build: ../fronted1
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=add
    command: ["flask", "run", "--host=0.0.0.0"]

  back:
    build: ../backend1
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=back
    command: ["flask", "run", "--host=0.0.0.0"]
