version: '3'
services:
  frontend1:
    build: .
    ports:
      - "5002:5002"
    depends_on:
      - nginx
    environment:
      - BACKEND_URL=http://localhost:5000

  backend1:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - backend1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
