version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - version=2.0
    image: frontend:2.0
    depends_on:
      - backend
    networks:
      - devops-network
    volumes:
      - ./data:/app/data
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - version=2.0
    image: backend:2.0
    networks:
      - devops-network
    volumes:
      - ./data:/app/data
    restart: always

networks:
  devops-network:
    driver: bridge
