services:
  backend:
    build: ./backend1
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=back
    command: ["flask", "run", "--host=0.0.0.0"]
  frontend:
    build: ./fronted1
    ports:
      - "5002:5000"
    environment:
      - FLASK_APP=add
    command: ["flask", "run", "--host=0.0.0.0"]
