services:
  backend1:
    build: ./backend1
    ports:
      - "5000:5000"
    networks:
      - backend-network

  frontend1:
    build: ./frontend1
    ports:
      - "5002:5002"
    depends_on:
      - backend1
    networks:
      - backend-network
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend1
      - backend1
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
