version: '3'
services:
  backend:
    build: C:\\Users\\tsika\\PycharmProjects\\DevOps\\backend1
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=back
    command: ["flask", "run", "--host=0.0.0.0"]
  frontend:
    build: C:\\Users\\tsika\\PycharmProjects\\DevOps\\frontend1
    ports:
      - "5002:5000"
