services:
  backend1:
    build: ../backend1
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: backend1
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000"]
    networks:
      - backend-network

  frontend1:
    build: ../frontend1
    ports:
      - "5002:5002"
    environment:
      DISPLAY: :99 
    command: ["sh", "-c", "Xvfb :99 -screen 0 1024x768x16 & python frontend1.py --host=0.0.0.0 --port=5002"]
    depends_on:
      - backend1
    networks:
      - backend-network
    extra_hosts:
      - "localhost:host-gateway"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - frontend1
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
