- name: Prepare environment
  hosts: all
  become: yes

  tasks:
    - name: Install Docker
      apt:
        name: docker-ce
        state: latest

    - name: Get latest Docker Compose version
      command: "curl -s https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d '\"' -f 4"
      register: compose_version

    - name: Install Docker Compose
        get_url:
          url: "https://github.com/docker/compose/releases/download/v2.31.0/docker-compose-{{ ansible_os_family | lower }}-{{ ansible_architecture }}"
          dest: /usr/local/bin/docker-compose
          mode: 'u+x'

    - name: Clone frontend repository
      git:
        repo: 'https://github.com/AlexanderTsikalo651/frontend1.git'
        dest: /home/alexander/Рабочий стол/DevOps/frontend1

    - name: Clone backend repository
      git:
        repo: 'https://github.com/AlexanderTsikalo651/backend1.git'
        dest: /home/alexander/Рабочий стол/DevOps/backend1

    - name: Clone DevOps repository
      git:
        repo: 'https://github.com/AlexanderTsikalo651/DevOps.git'
        dest: /home/alexander/Рабочий стол/DevOps/DevOps
        
- name: Start applications
  hosts: all
  become: yes

  tasks:
    - name: Start services with Docker Compose
      command: docker-compose up -d
      args:
        chdir: /home/alexander/Рабочий стол/DevOps/DevOps
