- name: Prepare environment
  hosts: all
  become: yes

  tasks:
    - name: Install Docker
      apt:
        name: docker-ce
        state: latest

    - name: Установка Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)
        dest: /usr/local/bin/docker-compose
        mode: 'u+x'

    - name: Clone frontend repository
      git:
        repo: 'https://github.com/AlexanderTsikalo651/frontend1.git'
        dest: /home/alexander/Рабочий стол/DevOps/frontend1

    - name: Clone backend repository
      git:
        repo: 'https://github.com/AlexanderTsikalo651/backend1.git'
        dest: /home/alexander/Рабочий стол/DevOps/backend1

    - name: Clone DevOps repository
      git:
        repo: 'https://github.com/AlexanderTsikalo651/DevOps.git'
        dest: /home/alexander/Рабочий стол/DevOps/DevOps

- name: Start applications
  hosts: all
  become: yes

  tasks:
    - name: Start services with Docker Compose
      command: docker-compose up -d
      args:
        chdir: /home/alexander/Рабочий стол/DevOps/DevOps
