---
- name: Prepare environment
  hosts: all
  become: yes

  tasks:
  - name: Install Docker
    apt:
      name: docker-ce
      state: latest

  - name: Install Docker Compose
    get_url:
      url: https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)
      dest: /usr/local/bin/docker-compose
      mode: 'u+x'

  - name: Clone repositories
    git:
      repo: 'https://github.com/AlexanderTsikalo651/frontend1.git'
      dest: /home/alexander/Рабочий стол/DevOps/frontend1
    git:
      repo: 'https://github.com/AlexanderTsikalo651/backend1.git'
      dest: /home/alexander/Рабочий стол/DevOps/backend1
    git:
      repo: 'https://github.com/AlexanderTsikalo651/DevOps.git'
      dest: /home/alexander/Рабочий стол/DevOps/DevOps
