- name: Start applications
  hosts: all
  become: yes

  tasks:
    - name: Проверка наличия файла docker-compose.yml
      stat:
        path: "/var/lib/jenkins/workspace/lr/DevOps/docker-compose.yml"
      register: compose_file

    - name: Ошибка, если файл docker-compose.yml не найден
      fail:
        msg: "Файл docker-compose.yml не найден в директории /var/lib/jenkins/workspace/lr/DevOps"
      when: not compose_file.stat.exists

    - name: Вывод текущей директории
      command: pwd
      register: current_directory

    - name: Печать текущей директории
      debug:
        var: current_directory.stdout

    - name: Запуск сервисов с помощью Docker Compose
      command: docker-compose up -d
      args:
        chdir: "/var/lib/jenkins/workspace/lr/DevOps"
      when: compose_file.stat.exists

    - name: Проверка прав доступа к docker-compose.yml
      command: ls -l /var/lib/jenkins/workspace/lr/DevOps/docker-compose.yml
      register: permissions_check

    - name: Печать прав доступа к файлу
      debug:
        var: permissions_check.stdout
