---
- name: Установка необходимых пакетов
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Добавление GPG ключа Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Добавление репозитория Docker
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
    state: present

- name: Установка Docker
  apt:
    name: docker-ce
    state: latest

- name: Установка Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)
    dest: /usr/local/bin/docker-compose
    mode: 'u+x'
